export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const USER_ERROR = "USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER"

export const GET_ITINERARY = "GET_ITINERARY";
export const GENERATE_ITINERARY = "GENERATE_ITINERARY";
export const STORE_DATE = "STORE_DATE";
export const LOADING_ITINERARY = "LOADING_ITINERARY";
export const ITINERARY_ERROR = "ITINERARY_ERROR";

export const GET_ALL_ATTRACTIONS = "GET_ALL_ATTRACTIONS";
export const GENERATED_ATTRACTION = "GENERATED_ATTRACTION";
export const ATTRACTION_ERROR = "ATTRACTION_ERROR";
